version: 2

sources:
  - name: localbike_dataset
    schema: localbike_dataset
    tables:
      - name: brands
      - name: categories
      - name: customers
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name: stores
      